### ISSUE TITLE
Validate lifetime variables

### ISSUE THREAD

**Issue by nseeba** [HEP-KBFI/ml-tau-en-reg#9]
- errors

- sign

**Comment by Laurits7** [comment]
As previously confirmed, the common lifetime variable values were confirmed to be correct. Now checking the sign and error of them also, we see that also these have correct values: The signed values of lifetime variables for tau should have some asymmetry while the values for qq jets should be symmetric. This is visible on the following plots:
![image](https://github.com/HEP-KBFI/ml-tau-en-reg/assets/30724920/d2eb95f9-2437-4f68-8786-6c8060782ce4)
![image](https://github.com/HEP-KBFI/ml-tau-en-reg/assets/30724920/30f0fb31-e0ca-4536-8808-c5ce51166a6d)

Values for the errors are also reasonable as seen here:
![image](https://github.com/HEP-KBFI/ml-tau-en-reg/assets/30724920/c53061d0-3130-4333-aea2-6d5072702e6d)

Conclusion: resolved

**Comment by Laurits7** [comment]
A brief summary of the problem: Due to false parent-daughter relationship of the genParticles, the genParticles (and therefore the genTau properties) are taken from the .hepmc file. However, the primary vertex (PV) in the .hepmc files is not located at 000 as it is in the key4hep files, therefore also the tau decay vertex (DV) is shifted. The track parameters (omega, lambda, etc.) from the key4hep format are still relative to PV@000. Therefore the tau DV is shifted into the same coordinates, fixing the problem with the calculated lifetime variables.
